In [14]:
import pandas as pd
import requests
import json

In [15]:
# response=requests.get("https://imdb.iamidiotareyoutoo.com/search?q=mark")

In [23]:
# response.json()

In [24]:
response = requests.get('https://newsapi.org/v2/everything?q=tesla&from=2026-05-26&sortBy=publishedAt&apiKey=4ae06953631d446187a2c9a796db97ea')

In [26]:
result=response.json()['articles']

In [36]:
df=pd.DataFrame(result)

In [37]:
df.shape

(97, 8)

In [51]:
df.head(1)

,source,author,title,description,url,urlToImage,publishedAt,content
0,"{'id': None, 'name': 'Hwupgrade.it'}",NaN,Attacco informatico a Tata: rubati dati sui pr...,Tata Electronics ha subito un attacco informat...,https://www.hwupgrade.it/news/web/attacco-info...,https://www.hwupgrade.it/i/n/Apple_speseADV_72...,2026-06-25T06:01:01Z,Tata Electronics ha confermato di aver subito ...

In [52]:
df= df.copy()
df['source'] = df['source'].apply(
    lambda x: x['name'] if isinstance(x, dict) else None
)
df.head()

,source,author,title,description,url,urlToImage,publishedAt,content
0,Hwupgrade.it,NaN,Attacco informatico a Tata: rubati dati sui pr...,Tata Electronics ha subito un attacco informat...,https://www.hwupgrade.it/news/web/attacco-info...,https://www.hwupgrade.it/i/n/Apple_speseADV_72...,2026-06-25T06:01:01Z,Tata Electronics ha confermato di aver subito ...
1,Naturalnews.com,Jacob Thomas,Scientists confirm: Sodium-ion batteries could...,A study in Cell Reports Physical Science confi...,https://www.naturalnews.com/2026-06-25-sodium-...,https://www.naturalnews.com/wp-content/uploads...,2026-06-25T06:00:00Z,<ul><li>A study in Cell Reports Physical Scien...
2,Prtimes.jp,NaN,世界で最もテスラが安い街、東京,[Tesla Japan 合同会社]\n[画像1: https://prcdn.freetl...,https://prtimes.jp/main/html/rd/p/000000066.00...,https://prcdn.freetls.fastly.net/release_image...,2026-06-25T05:40:41Z,"2026624EVCEV127ZEV4030Model 3 RWD¥3,343,000 \r..."
3,Ixbt.com,Jin,"Телепатия станет реальностью? Маск заявил, что...",Идея предполагает общение без слов и жестов,https://www.ixbt.com/news/2026/06/25/telepatij...,https://media.ixbt.site/1600x900/smart/https:/...,2026-06-25T04:59:00Z,"Neuralink 2026 . , , , «».\r\n Tesla, , - (Yun..."
4,Ixbt.com,Jin,Tesla и GIGA Storage готовят гигантскую батаре...,Новая система накопления энергии станет одним ...,https://www.ixbt.com/news/2026/06/25/tesla-gig...,https://media.ixbt.site/1600x900/smart/https:/...,2026-06-25T04:55:00Z,"Tesla GIGA Storage Green Turtle .\r\n - (, ) 7..."

In [53]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   source       97 non-null     str
 1   author       88 non-null     str
 2   title        97 non-null     str
 3   description  97 non-null     str
 4   url          97 non-null     str
 5   urlToImage   92 non-null     str
 6   publishedAt  97 non-null     str
 7   content      97 non-null     str
dtypes: str(8)
memory usage: 78.2 KB

In [54]:
df.drop(columns=['description','content'],inplace=True)

In [55]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   source       97 non-null     str
 1   author       88 non-null     str
 2   title        97 non-null     str
 3   url          97 non-null     str
 4   urlToImage   92 non-null     str
 5   publishedAt  97 non-null     str
dtypes: str(6)
memory usage: 36.3 KB

In [56]:
df.rename(columns={'source':'sourceName','author':'authorName','url':'sourceUrl','urlToImage':'PostUrl','publishedAt':'publishedDate'},inplace=True)

In [57]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   sourceName     97 non-null     str
 1   authorName     88 non-null     str
 2   title          97 non-null     str
 3   sourceUrl      97 non-null     str
 4   PostUrl        92 non-null     str
 5   publishedDate  97 non-null     str
dtypes: str(6)
memory usage: 36.3 KB

In [58]:
df.to_csv('News.csv',index=False)