# *IMPORTING PANDAS*

In [ ]:
import pandas as pd

# *<b style="color:'aqua' background-color:'red'">Opening a local csv file</b>*

In [1]:
df=pd.read_csv("flights_tickets_serp2020-04-01.csv")
df

,searchTerms,rank,title,snippet,displayLink,link,queryTime,totalResults,cacheId,formattedUrl,...,count,startIndex,inputEncoding,outputEncoding,safe,cx,gl,searchTime,formattedSearchTime,formattedTotalResults
0,flights to hong kong,1,"$103 Flights to Hong Kong, China (HKG) - Tripa...",Book Cheap Flights to Hong Kong: Search and co...,www.tripadvisor.com,https://www.tripadvisor.com/Flights-g294217-Ho...,2020-04-01 11:25:53.059369+00:00,178000000,5jsjhmxgxvkJ,https://www.tripadvisor.com/Flights-g294217-Ho...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.482802,0.48,"178,000,000"
1,flights to hong kong,2,Flights to Hong Kong (HKG) | Cathay Pacific,Find & book great deals on Hong Kong (HKG) Fli...,www.cathaypacific.com,https://www.cathaypacific.com/destinations/en_...,2020-04-01 11:25:53.059369+00:00,178000000,UEdjkoYlsQsJ,https://www.cathaypacific.com/destinations/en_...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.482802,0.48,"178,000,000"
2,flights to hong kong,3,"Cheap Flights to Hong Kong SAR, Asia (HKG Airp...",Looking for cheap flights to Hong Kong SAR fro...,www.expedia.com,https://www.expedia.com/Cheap-Flights-To-Hong-...,2020-04-01 11:25:53.059369+00:00,178000000,iEmRbX0P8CAJ,https://www.expedia.com/Cheap-Flights-To-Hong-...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.482802,0.48,"178,000,000"
3,flights to hong kong,4,Cheap Flights to Hong Kong (HKG) from $487 - K...,"Find flights to Hong Kong on China Eastern, As...",www.kayak.com,https://www.kayak.com/flight-routes/United-Sta...,2020-04-01 11:25:53.059369+00:00,178000000,W42baDpas_gJ,https://www.kayak.com/flight-routes/United-Sta...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.482802,0.48,"178,000,000"
4,flights to hong kong,5,$404 Cheap Flights to Hong Kong Intl in 2020 |...,Find cheap flights to Hong Kong Intl (HKG) in ...,www.skyscanner.com,https://www.skyscanner.com/flights-to/hkg/chea...,2020-04-01 11:25:53.059369+00:00,178000000,YU4I4h8FLkwJ,https://www.skyscanner.com/flights-to/hkg/chea...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.482802,0.48,"178,000,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,tickets to nice,6,OGC Nice official website,"OGC Nice. The line-ups are in, it's almost tim...",m.ogcnice.com,https://m.ogcnice.com/en/,2020-04-01 11:26:00.956144+00:00,416000000,6-RI9U-9HOAJ,https://m.ogcnice.com/en/,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.355928,0.36,"416,000,000"
3996,tickets to nice,7,Options for buying train tickets in Nice - Nic...,Answer 1 of 15: I will be in Nice for about a ...,www.tripadvisor.co.uk,https://www.tripadvisor.co.uk/ShowTopic-g18723...,2020-04-01 11:26:00.956144+00:00,416000000,-EHN3x0HuA8J,https://www.tripadvisor.co.uk/ShowTopic-g18723...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.355928,0.36,"416,000,000"
3997,tickets to nice,8,Nice to Milan by Train from €15 | Book Direct ...,Travel by train from Nice to Milan in 4h 44m. ...,www.thetrainline.com,https://www.thetrainline.com/en/train-times/ni...,2020-04-01 11:26:00.956144+00:00,416000000,p49hSZHKcIsJ,https://www.thetrainline.com/en/train-times/ni...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.355928,0.36,"416,000,000"
3998,tickets to nice,9,NFC Nice Ticket - Lignes d'Azur,NFC Nice Ticket is a mobile application which ...,www.lignesdazur.com,https://www.lignesdazur.com/en/nfc-nice-ticket...,2020-04-01 11:26:00.956144+00:00,416000000,lljcmWGds38J,https://www.lignesdazur.com/en/nfc-nice-ticket...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.355928,0.36,"416,000,000"
3999,tickets to nice,10,Nice to Florence by Train from €31.80 | France...,"With no direct flights from Nice to Florence, ...",www.thetrainline.com,https://www.thetrainline.com/en/train-times/ni...,2020-04-01 11:26:00.956144+00:00,416000000,SXhgYbLnqR8J,https://www.thetrainline.com/en/train-times/ni...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.355928,0.36,"416,000,000"

<h1 style="color:red; background:aqua'">Opening a csv file from an Url</h1>

In [2]:
import pandas as pd
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"

headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"
}

req = requests.get(url, headers=headers)
data = StringIO(req.text)

df = pd.read_csv(data)
df

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

## Sep Parameter

In [3]:
df1=pd.read_csv("titanic.tsv")
df1

,1\t0\t3\tBraund,Mr. Owen Harris\tmale\t22\t1\t0\tA/5 21171\t7.25\t\N\tS
0,2\t1\t1\tCumings,Mrs. John Bradley (Florence Briggs Thayer)\tf...
1,3\t1\t3\tHeikkinen,Miss. Laina\tfemale\t26\t0\t0\tSTON/O2. 31012...
2,4\t1\t1\tFutrelle,Mrs. Jacques Heath (Lily May Peel)\tfemale\t3...
3,5\t0\t3\tAllen,Mr. William Henry\tmale\t35\t0\t0\t373450\t8....
4,6\t0\t3\tMoran,Mr. James\tmale\t\N\t0\t0\t330877\t8.4583\t\N\tQ
...,...,...
885,887\t0\t2\tMontvila,Rev. Juozas\tmale\t27\t0\t0\t211536\t13\t\N\tS
886,888\t1\t1\tGraham,Miss. Margaret Edith\tfemale\t19\t0\t0\t11205...
887,889\t0\t3\tJohnston,"Miss. Catherine Helen ""Carrie""\tfemale\t\N\t1..."
888,890\t1\t1\tBehr,Mr. Karl Howell\tmale\t26\t0\t0\t111369\t30\t...
889,891\t0\t3\tDooley,Mr. Patrick\tmale\t32\t0\t0\t370376\t7.75\t\N\tQ

In [6]:
df2=pd.read_csv("titanic.tsv",sep="\t")# sep="\t" is used because data is separated by the tab by default sep valued is set as comma
df2 # Here is no name for columns. So use names parameter

,1,0,3,"Braund, Mr. Owen Harris",male,22,1.1,0.1,A/5 21171,7.25,\N,S
0,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
1,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,\N,S
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
3,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,\N,S
4,6,0,3,"Moran, Mr. James",male,\N,0,0,330877,8.4583,\N,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
885,887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13.0000,\N,S
886,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.0000,B42,S
887,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,\N,1,2,W./C. 6607,23.4500,\N,S
888,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.0000,C148,C
889,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.7500,\N,Q

## Name parameter

In [10]:
df2=pd.read_csv("titanic.tsv",sep="\t",names=['Sr.No.','Val1','Val2','Name','Gender',"Age","Val3","Val4","Address","Street No.","Counting","Marks"])

In [11]:
df2

,Sr.No.,Val1,Val2,Name,Gender,Age,Val3,Val4,Address,Street No.,Counting,Marks
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,\N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,\N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,\N,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13.0000,\N,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,\N,1,2,W./C. 6607,23.4500,\N,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.7500,\N,Q

In [12]:
pd.read_csv("flights_tickets_serp2019-01-15.csv")

,searchTerms,rank,title,snippet,displayLink,link,queryTime,totalResults,cacheId,formattedUrl,...,count,startIndex,inputEncoding,outputEncoding,safe,cx,gl,searchTime,formattedSearchTime,formattedTotalResults
0,flights to hong kong,1,Cheap Flights to Hong Kong (HKG) from $384 - K...,"Find flights to Hong Kong on XiamenAir, Hong K...",www.kayak.com,https://www.kayak.com/flight-routes/United-Sta...,2019-01-15 11:26:21.040640+00:00,120000000,W42baDpas_gJ,https://www.kayak.com/flight-routes/United.../...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.444640,0.44,"120,000,000"
1,flights to hong kong,2,"$506 Flights to Hong Kong, China (HKG) - TripA...",Book Cheap Flights to Hong Kong: Search and co...,www.tripadvisor.com,https://www.tripadvisor.com/Flights-g294217-Ho...,2019-01-15 11:26:21.040640+00:00,120000000,5jsjhmxgxvkJ,https://www.tripadvisor.com/Flights-g294217-Ho...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.444640,0.44,"120,000,000"
2,flights to hong kong,3,Flights to Hong Kong (HKG) | Cathay Pacific,Find & book great deals on Hong Kong (HKG) Fli...,flights.cathaypacific.com,https://flights.cathaypacific.com/en-us/flight...,2019-01-15 11:26:21.040640+00:00,120000000,q6kszaD7mggJ,https://flights.cathaypacific.com/en-us/flight...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.444640,0.44,"120,000,000"
3,flights to hong kong,4,Cheap Flights to Hong Kong International from ...,Find cheap flights to Hong Kong International ...,www.skyscanner.com,https://www.skyscanner.com/flights-to/hkg/chea...,2019-01-15 11:26:21.040640+00:00,120000000,EI78TI4Q1qYJ,https://www.skyscanner.com/flights-to/hkg/chea...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.444640,0.44,"120,000,000"
4,flights to hong kong,5,"Cheap Flights to Hong Kong SAR, Asia $161 in 2...",Expedia Add-On Advantage: Book a flight & unlo...,www.expedia.com,https://www.expedia.com/Cheap-Flights-To-Hong-...,2019-01-15 11:26:21.040640+00:00,120000000,iEmRbX0P8CAJ,https://www.expedia.com/Cheap-Flights-To-Hong-...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.444640,0.44,"120,000,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,tickets to nice,6,Cheap Flights to Nice from £20 - Cheapflights....,The simple way to find cheap flights to Nice. ...,www.cheapflights.co.uk,https://www.cheapflights.co.uk/flights/Nice/,2019-01-15 11:26:35.555108+00:00,317000000,DYKF0V7wOPgJ,https://www.cheapflights.co.uk/flights/Nice/,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.277256,0.28,"317,000,000"
3996,tickets to nice,7,Billetterie Officielle OGC Nice,"To simplify your research, use filters. Filter...",billetterie.ogcnice.com,https://billetterie.ogcnice.com/uk,2019-01-15 11:26:35.555108+00:00,317000000,oOOabhwvUmYJ,https://billetterie.ogcnice.com/uk,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.277256,0.28,"317,000,000"
3997,tickets to nice,8,Cheap flights to Nice from £15 - Book trips to...,The city of Nice is served by the Nice Côte d'...,www.opodo.co.uk,https://www.opodo.co.uk/flights/nice/NCE/,2019-01-15 11:26:35.555108+00:00,317000000,_lZDrsS7w7oJ,https://www.opodo.co.uk/flights/nice/NCE/,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.277256,0.28,"317,000,000"
3998,tickets to nice,9,OGC Nice Tickets | Buy or Sell Tickets for OGC...,OGC Nice tickets now available from £4.47 as o...,www.viagogo.co.uk,https://www.viagogo.co.uk/Sports-Tickets/Footb...,2019-01-15 11:26:35.555108+00:00,317000000,CaSToMNESN4J,https://www.viagogo.co.uk/Sports-Tickets/...1/...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.277256,0.28,"317,000,000"
3999,tickets to nice,10,5 Cheap Flights to Nice @ £41 2018 - TripAdvisor,Cheap Flights to Nice: Enter your dates once a...,www.tripadvisor.co.uk,https://www.tripadvisor.co.uk/Flights-g187234-...,2019-01-15 11:26:35.555108+00:00,317000000,1-sONufbuo8J,https://www.tripadvisor.co.uk/Flights-g187234-...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.277256,0.28,"317,000,000"

# Index_col Parameter

In [13]:
pd.read_csv("flights_tickets_serp2019-01-15.csv",index_col="searchTerms")

,rank,title,snippet,displayLink,link,queryTime,totalResults,cacheId,formattedUrl,htmlFormattedUrl,...,count,startIndex,inputEncoding,outputEncoding,safe,cx,gl,searchTime,formattedSearchTime,formattedTotalResults
searchTerms,,,,,,,,,,,,,,,,,,,,,
flights to hong kong,1,Cheap Flights to Hong Kong (HKG) from $384 - K...,"Find flights to Hong Kong on XiamenAir, Hong K...",www.kayak.com,https://www.kayak.com/flight-routes/United-Sta...,2019-01-15 11:26:21.040640+00:00,120000000,W42baDpas_gJ,https://www.kayak.com/flight-routes/United.../...,https://www.kayak.com/<b>flight</b>-routes/Uni...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.444640,0.44,"120,000,000"
flights to hong kong,2,"$506 Flights to Hong Kong, China (HKG) - TripA...",Book Cheap Flights to Hong Kong: Search and co...,www.tripadvisor.com,https://www.tripadvisor.com/Flights-g294217-Ho...,2019-01-15 11:26:21.040640+00:00,120000000,5jsjhmxgxvkJ,https://www.tripadvisor.com/Flights-g294217-Ho...,https://www.tripadvisor.com/<b>Flights</b>-g29...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.444640,0.44,"120,000,000"
flights to hong kong,3,Flights to Hong Kong (HKG) | Cathay Pacific,Find & book great deals on Hong Kong (HKG) Fli...,flights.cathaypacific.com,https://flights.cathaypacific.com/en-us/flight...,2019-01-15 11:26:21.040640+00:00,120000000,q6kszaD7mggJ,https://flights.cathaypacific.com/en-us/flight...,https://<b>flights</b>.cathaypacific.com/en-us...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.444640,0.44,"120,000,000"
flights to hong kong,4,Cheap Flights to Hong Kong International from ...,Find cheap flights to Hong Kong International ...,www.skyscanner.com,https://www.skyscanner.com/flights-to/hkg/chea...,2019-01-15 11:26:21.040640+00:00,120000000,EI78TI4Q1qYJ,https://www.skyscanner.com/flights-to/hkg/chea...,https://www.skyscanner.com/<b>flights-to/hk</b...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.444640,0.44,"120,000,000"
flights to hong kong,5,"Cheap Flights to Hong Kong SAR, Asia $161 in 2...",Expedia Add-On Advantage: Book a flight & unlo...,www.expedia.com,https://www.expedia.com/Cheap-Flights-To-Hong-...,2019-01-15 11:26:21.040640+00:00,120000000,iEmRbX0P8CAJ,https://www.expedia.com/Cheap-Flights-To-Hong-...,https://www.expedia.com/Cheap-<b>Flights-To-Ho...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.444640,0.44,"120,000,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
tickets to nice,6,Cheap Flights to Nice from £20 - Cheapflights....,The simple way to find cheap flights to Nice. ...,www.cheapflights.co.uk,https://www.cheapflights.co.uk/flights/Nice/,2019-01-15 11:26:35.555108+00:00,317000000,DYKF0V7wOPgJ,https://www.cheapflights.co.uk/flights/Nice/,https://www.cheap<b>flights</b>.co.uk/<b>fligh...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.277256,0.28,"317,000,000"
tickets to nice,7,Billetterie Officielle OGC Nice,"To simplify your research, use filters. Filter...",billetterie.ogcnice.com,https://billetterie.ogcnice.com/uk,2019-01-15 11:26:35.555108+00:00,317000000,oOOabhwvUmYJ,https://billetterie.ogcnice.com/uk,https://billetterie.ogc<b>nice</b>.com/uk,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.277256,0.28,"317,000,000"
tickets to nice,8,Cheap flights to Nice from £15 - Book trips to...,The city of Nice is served by the Nice Côte d'...,www.opodo.co.uk,https://www.opodo.co.uk/flights/nice/NCE/,2019-01-15 11:26:35.555108+00:00,317000000,_lZDrsS7w7oJ,https://www.opodo.co.uk/flights/nice/NCE/,https://www.opodo.co.uk/<b>flights</b>/<b>nice...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.277256,0.28,"317,000,000"
tickets to nice,9,OGC Nice Tickets | Buy or Sell Tickets for OGC...,OGC Nice tickets now available from £4.47 as o...,www.viagogo.co.uk,https://www.viagogo.co.uk/Sports-Tickets/Footb...,2019-01-15 11:26:35.555108+00:00,317000000,CaSToMNESN4J,https://www.viagogo.co.uk/Sports-Tickets/...1/...,https://www.viagogo.co.uk/Sports-<b>Tickets</b...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.277256,0.28,"317,000,000"
tickets to nice,10,5 Cheap Flights to Nice @ £41 2018 - TripAdvisor,Cheap Flights to Nice: Enter your dates once a...,www.tripadvisor.co.uk,https://www.tripadvisor.co.uk/Flights-g187234-...,2019-01-15 11:26:35.555108+00:00,317000000,1-sONufbuo8J,https://www.tripadvisor.co.uk/Flights-g187234-...,https://www.tripadvisor.co.uk/<b>Flights</b>-g...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.277256,0.28,"317,000,000"

# Header Parameter

In [14]:
pd.read_csv("flights_tickets_serp2019-01-15.csv")

,searchTerms,rank,title,snippet,displayLink,link,queryTime,totalResults,cacheId,formattedUrl,...,count,startIndex,inputEncoding,outputEncoding,safe,cx,gl,searchTime,formattedSearchTime,formattedTotalResults
0,flights to hong kong,1,Cheap Flights to Hong Kong (HKG) from $384 - K...,"Find flights to Hong Kong on XiamenAir, Hong K...",www.kayak.com,https://www.kayak.com/flight-routes/United-Sta...,2019-01-15 11:26:21.040640+00:00,120000000,W42baDpas_gJ,https://www.kayak.com/flight-routes/United.../...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.444640,0.44,"120,000,000"
1,flights to hong kong,2,"$506 Flights to Hong Kong, China (HKG) - TripA...",Book Cheap Flights to Hong Kong: Search and co...,www.tripadvisor.com,https://www.tripadvisor.com/Flights-g294217-Ho...,2019-01-15 11:26:21.040640+00:00,120000000,5jsjhmxgxvkJ,https://www.tripadvisor.com/Flights-g294217-Ho...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.444640,0.44,"120,000,000"
2,flights to hong kong,3,Flights to Hong Kong (HKG) | Cathay Pacific,Find & book great deals on Hong Kong (HKG) Fli...,flights.cathaypacific.com,https://flights.cathaypacific.com/en-us/flight...,2019-01-15 11:26:21.040640+00:00,120000000,q6kszaD7mggJ,https://flights.cathaypacific.com/en-us/flight...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.444640,0.44,"120,000,000"
3,flights to hong kong,4,Cheap Flights to Hong Kong International from ...,Find cheap flights to Hong Kong International ...,www.skyscanner.com,https://www.skyscanner.com/flights-to/hkg/chea...,2019-01-15 11:26:21.040640+00:00,120000000,EI78TI4Q1qYJ,https://www.skyscanner.com/flights-to/hkg/chea...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.444640,0.44,"120,000,000"
4,flights to hong kong,5,"Cheap Flights to Hong Kong SAR, Asia $161 in 2...",Expedia Add-On Advantage: Book a flight & unlo...,www.expedia.com,https://www.expedia.com/Cheap-Flights-To-Hong-...,2019-01-15 11:26:21.040640+00:00,120000000,iEmRbX0P8CAJ,https://www.expedia.com/Cheap-Flights-To-Hong-...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.444640,0.44,"120,000,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,tickets to nice,6,Cheap Flights to Nice from £20 - Cheapflights....,The simple way to find cheap flights to Nice. ...,www.cheapflights.co.uk,https://www.cheapflights.co.uk/flights/Nice/,2019-01-15 11:26:35.555108+00:00,317000000,DYKF0V7wOPgJ,https://www.cheapflights.co.uk/flights/Nice/,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.277256,0.28,"317,000,000"
3996,tickets to nice,7,Billetterie Officielle OGC Nice,"To simplify your research, use filters. Filter...",billetterie.ogcnice.com,https://billetterie.ogcnice.com/uk,2019-01-15 11:26:35.555108+00:00,317000000,oOOabhwvUmYJ,https://billetterie.ogcnice.com/uk,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.277256,0.28,"317,000,000"
3997,tickets to nice,8,Cheap flights to Nice from £15 - Book trips to...,The city of Nice is served by the Nice Côte d'...,www.opodo.co.uk,https://www.opodo.co.uk/flights/nice/NCE/,2019-01-15 11:26:35.555108+00:00,317000000,_lZDrsS7w7oJ,https://www.opodo.co.uk/flights/nice/NCE/,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.277256,0.28,"317,000,000"
3998,tickets to nice,9,OGC Nice Tickets | Buy or Sell Tickets for OGC...,OGC Nice tickets now available from £4.47 as o...,www.viagogo.co.uk,https://www.viagogo.co.uk/Sports-Tickets/Footb...,2019-01-15 11:26:35.555108+00:00,317000000,CaSToMNESN4J,https://www.viagogo.co.uk/Sports-Tickets/...1/...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.277256,0.28,"317,000,000"
3999,tickets to nice,10,5 Cheap Flights to Nice @ £41 2018 - TripAdvisor,Cheap Flights to Nice: Enter your dates once a...,www.tripadvisor.co.uk,https://www.tripadvisor.co.uk/Flights-g187234-...,2019-01-15 11:26:35.555108+00:00,317000000,1-sONufbuo8J,https://www.tripadvisor.co.uk/Flights-g187234-...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.277256,0.28,"317,000,000"

In [17]:
pd.read_csv("flights_tickets_serp2019-01-15.csv",header=0)#Header=0 is define the starting point of your rows

,searchTerms,rank,title,snippet,displayLink,link,queryTime,totalResults,cacheId,formattedUrl,...,count,startIndex,inputEncoding,outputEncoding,safe,cx,gl,searchTime,formattedSearchTime,formattedTotalResults
0,flights to hong kong,1,Cheap Flights to Hong Kong (HKG) from $384 - K...,"Find flights to Hong Kong on XiamenAir, Hong K...",www.kayak.com,https://www.kayak.com/flight-routes/United-Sta...,2019-01-15 11:26:21.040640+00:00,120000000,W42baDpas_gJ,https://www.kayak.com/flight-routes/United.../...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.444640,0.44,"120,000,000"
1,flights to hong kong,2,"$506 Flights to Hong Kong, China (HKG) - TripA...",Book Cheap Flights to Hong Kong: Search and co...,www.tripadvisor.com,https://www.tripadvisor.com/Flights-g294217-Ho...,2019-01-15 11:26:21.040640+00:00,120000000,5jsjhmxgxvkJ,https://www.tripadvisor.com/Flights-g294217-Ho...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.444640,0.44,"120,000,000"
2,flights to hong kong,3,Flights to Hong Kong (HKG) | Cathay Pacific,Find & book great deals on Hong Kong (HKG) Fli...,flights.cathaypacific.com,https://flights.cathaypacific.com/en-us/flight...,2019-01-15 11:26:21.040640+00:00,120000000,q6kszaD7mggJ,https://flights.cathaypacific.com/en-us/flight...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.444640,0.44,"120,000,000"
3,flights to hong kong,4,Cheap Flights to Hong Kong International from ...,Find cheap flights to Hong Kong International ...,www.skyscanner.com,https://www.skyscanner.com/flights-to/hkg/chea...,2019-01-15 11:26:21.040640+00:00,120000000,EI78TI4Q1qYJ,https://www.skyscanner.com/flights-to/hkg/chea...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.444640,0.44,"120,000,000"
4,flights to hong kong,5,"Cheap Flights to Hong Kong SAR, Asia $161 in 2...",Expedia Add-On Advantage: Book a flight & unlo...,www.expedia.com,https://www.expedia.com/Cheap-Flights-To-Hong-...,2019-01-15 11:26:21.040640+00:00,120000000,iEmRbX0P8CAJ,https://www.expedia.com/Cheap-Flights-To-Hong-...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.444640,0.44,"120,000,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,tickets to nice,6,Cheap Flights to Nice from £20 - Cheapflights....,The simple way to find cheap flights to Nice. ...,www.cheapflights.co.uk,https://www.cheapflights.co.uk/flights/Nice/,2019-01-15 11:26:35.555108+00:00,317000000,DYKF0V7wOPgJ,https://www.cheapflights.co.uk/flights/Nice/,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.277256,0.28,"317,000,000"
3996,tickets to nice,7,Billetterie Officielle OGC Nice,"To simplify your research, use filters. Filter...",billetterie.ogcnice.com,https://billetterie.ogcnice.com/uk,2019-01-15 11:26:35.555108+00:00,317000000,oOOabhwvUmYJ,https://billetterie.ogcnice.com/uk,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.277256,0.28,"317,000,000"
3997,tickets to nice,8,Cheap flights to Nice from £15 - Book trips to...,The city of Nice is served by the Nice Côte d'...,www.opodo.co.uk,https://www.opodo.co.uk/flights/nice/NCE/,2019-01-15 11:26:35.555108+00:00,317000000,_lZDrsS7w7oJ,https://www.opodo.co.uk/flights/nice/NCE/,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.277256,0.28,"317,000,000"
3998,tickets to nice,9,OGC Nice Tickets | Buy or Sell Tickets for OGC...,OGC Nice tickets now available from £4.47 as o...,www.viagogo.co.uk,https://www.viagogo.co.uk/Sports-Tickets/Footb...,2019-01-15 11:26:35.555108+00:00,317000000,CaSToMNESN4J,https://www.viagogo.co.uk/Sports-Tickets/...1/...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.277256,0.28,"317,000,000"
3999,tickets to nice,10,5 Cheap Flights to Nice @ £41 2018 - TripAdvisor,Cheap Flights to Nice: Enter your dates once a...,www.tripadvisor.co.uk,https://www.tripadvisor.co.uk/Flights-g187234-...,2019-01-15 11:26:35.555108+00:00,317000000,1-sONufbuo8J,https://www.tripadvisor.co.uk/Flights-g187234-...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.277256,0.28,"317,000,000"

# use_cols Parameter

In [19]:
pd.read_csv("flights_tickets_serp2019-02-01.csv").info()

<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 26 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   searchTerms            4000 non-null   str
 1   rank                   4000 non-null   int64
 2   title                  4000 non-null   str
 3   snippet                3999 non-null   str
 4   displayLink            4000 non-null   str
 5   link                   4000 non-null   str
 6   queryTime              4000 non-null   str
 7   totalResults           4000 non-null   int64
 8   cacheId                3971 non-null   str
 9   formattedUrl           4000 non-null   str
 10  htmlFormattedUrl       4000 non-null   str
 11  htmlSnippet            3999 non-null   str
 12  htmlTitle              4000 non-null   str
 13  kind                   4000 non-null   str
 14  pagemap                3997 non-null   str
 15  cseName                4000 non-null   str
 16  count                  4000 non-null   int64
 17  startIndex             4000 non-null   int64
 18  inputEncoding          4000 non-null   str
 19  outputEncoding         4000 non-null   str
 20  safe                   4000 non-null   str
 21  cx                     4000 non-null   str
 22  gl                     4000 non-null   str
 23  searchTime             4000 non-null   float64
 24  formattedSearchTime    4000 non-null   float64
 25  formattedTotalResults  4000 non-null   str
dtypes: float64(2), int64(4), str(20)
memory usage: 9.5 MB

In [20]:
pd.read_csv("flights_tickets_serp2019-02-01.csv",usecols=['searchTerms','link','htmlTitle','safe','searchTime'])
# usecols is used to define which columns you want to use in dataframe

,searchTerms,link,htmlTitle,safe,searchTime
0,flights to hong kong,https://www.kayak.com/flight-routes/United-Sta...,Cheap <b>Flights to Hong Kong</b> (HKG) from $...,off,0.462434
1,flights to hong kong,https://www.tripadvisor.com/Flights-g294217-Ho...,"$500 <b>Flights to Hong Kong</b>, China (HKG) ...",off,0.462434
2,flights to hong kong,https://www.cathaypacific.com/destinations/en_...,<b>Flights to Hong Kong</b> (HKG) | Cathay Pac...,off,0.462434
3,flights to hong kong,https://www.skyscanner.com/flights-to/hkg/chea...,Cheap <b>Flights to Hong Kong</b> Internationa...,off,0.462434
4,flights to hong kong,https://www.expedia.com/Cheap-Flights-To-Hong-...,"Cheap <b>Flights to Hong Kong</b> SAR, Asia $1...",off,0.462434
...,...,...,...,...,...
3995,tickets to nice,https://billetterie.ogcnice.com/uk,Billetterie Officielle OGC <b>Nice</b>,off,0.279275
3996,tickets to nice,https://www.opodo.co.uk/flights/nice/NCE/,Cheap <b>flights to Nice</b> from £22 - Book t...,off,0.279275
3997,tickets to nice,https://www.viagogo.co.uk/Sports-Tickets/Footb...,OGC <b>Nice Tickets</b> | Buy or Sell <b>Ticke...,off,0.279275
3998,tickets to nice,https://www.tripadvisor.co.uk/Flights-g187234-...,"5 Cheap <b>Flights to Nice</b>, France (NCE) @...",off,0.279275
3999,tickets to nice,https://www.klm.com/en-gb/flights-to-nice,<b>Flights to Nice</b> (NCE) | KLM Nice ticket...,off,0.279275

# Squeeze Parameter

In [24]:
#pd.read_csv("flights_tickets_serp2019-02-01.csv",usecols=['title'],squeeze=True)      # Remove from the pandas new version
df = pd.read_csv("flights_tickets_serp2019-02-01.csv",
                 usecols=['title'])

series = df.squeeze("columns")

In [25]:
series

0       Cheap Flights to Hong Kong (HKG) from $400 - K...
1       $500 Flights to Hong Kong, China (HKG) - TripA...
2             Flights to Hong Kong (HKG) | Cathay Pacific
3       Cheap Flights to Hong Kong International from ...
4       Cheap Flights to Hong Kong SAR, Asia $165 in 2...
                              ...
3995                      Billetterie Officielle OGC Nice
3996    Cheap flights to Nice from £22 - Book trips to...
3997    OGC Nice Tickets | Buy or Sell Tickets for OGC...
3998    5 Cheap Flights to Nice, France (NCE) @ £26 20...
3999    Flights to Nice (NCE) | KLM Nice tickets from ...
Name: title, Length: 4000, dtype: str

# skiprows/nrows parameter

In [33]:
pd.read_csv("flights_tickets_serp2019-02-01.csv").head()

,searchTerms,rank,title,snippet,displayLink,link,queryTime,totalResults,cacheId,formattedUrl,...,count,startIndex,inputEncoding,outputEncoding,safe,cx,gl,searchTime,formattedSearchTime,formattedTotalResults
0,flights to hong kong,1,Cheap Flights to Hong Kong (HKG) from $400 - K...,"Find flights to Hong Kong on XiamenAir, Hong K...",www.kayak.com,https://www.kayak.com/flight-routes/United-Sta...,2019-02-01 11:26:20.355926+00:00,137000000,W42baDpas_gJ,https://www.kayak.com/flight-routes/United.../...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.462434,0.46,"137,000,000"
1,flights to hong kong,2,"$500 Flights to Hong Kong, China (HKG) - TripA...",Book Cheap Flights to Hong Kong: Search and co...,www.tripadvisor.com,https://www.tripadvisor.com/Flights-g294217-Ho...,2019-02-01 11:26:20.355926+00:00,137000000,5jsjhmxgxvkJ,https://www.tripadvisor.com/Flights-g294217-Ho...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.462434,0.46,"137,000,000"
2,flights to hong kong,3,Flights to Hong Kong (HKG) | Cathay Pacific,Find & book great deals on Hong Kong (HKG) Fli...,www.cathaypacific.com,https://www.cathaypacific.com/destinations/en_...,2019-02-01 11:26:20.355926+00:00,137000000,UEdjkoYlsQsJ,https://www.cathaypacific.com/destinations/en....,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.462434,0.46,"137,000,000"
3,flights to hong kong,4,Cheap Flights to Hong Kong International from ...,Find cheap flights to Hong Kong International ...,www.skyscanner.com,https://www.skyscanner.com/flights-to/hkg/chea...,2019-02-01 11:26:20.355926+00:00,137000000,EI78TI4Q1qYJ,https://www.skyscanner.com/flights-to/hkg/chea...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.462434,0.46,"137,000,000"
4,flights to hong kong,5,"Cheap Flights to Hong Kong SAR, Asia $165 in 2...",Expedia Add-On Advantage: Book a flight & unlo...,www.expedia.com,https://www.expedia.com/Cheap-Flights-To-Hong-...,2019-02-01 11:26:20.355926+00:00,137000000,iEmRbX0P8CAJ,https://www.expedia.com/Cheap-Flights-To-Hong-...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.462434,0.46,"137,000,000"

In [34]:
pd.read_csv("flights_tickets_serp2019-02-01.csv",skiprows=[2,5])

,searchTerms,rank,title,snippet,displayLink,link,queryTime,totalResults,cacheId,formattedUrl,...,count,startIndex,inputEncoding,outputEncoding,safe,cx,gl,searchTime,formattedSearchTime,formattedTotalResults
0,flights to hong kong,1,Cheap Flights to Hong Kong (HKG) from $400 - K...,"Find flights to Hong Kong on XiamenAir, Hong K...",www.kayak.com,https://www.kayak.com/flight-routes/United-Sta...,2019-02-01 11:26:20.355926+00:00,137000000,W42baDpas_gJ,https://www.kayak.com/flight-routes/United.../...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.462434,0.46,"137,000,000"
1,flights to hong kong,3,Flights to Hong Kong (HKG) | Cathay Pacific,Find & book great deals on Hong Kong (HKG) Fli...,www.cathaypacific.com,https://www.cathaypacific.com/destinations/en_...,2019-02-01 11:26:20.355926+00:00,137000000,UEdjkoYlsQsJ,https://www.cathaypacific.com/destinations/en....,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.462434,0.46,"137,000,000"
2,flights to hong kong,4,Cheap Flights to Hong Kong International from ...,Find cheap flights to Hong Kong International ...,www.skyscanner.com,https://www.skyscanner.com/flights-to/hkg/chea...,2019-02-01 11:26:20.355926+00:00,137000000,EI78TI4Q1qYJ,https://www.skyscanner.com/flights-to/hkg/chea...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.462434,0.46,"137,000,000"
3,flights to hong kong,6,Cheap Flights to Hong Kong - Search Deals on A...,Looking for cheap flights to Hong Kong from yo...,www.cheapflights.com,https://www.cheapflights.com/flights-to-hong-k...,2019-02-01 11:26:20.355926+00:00,137000000,INTDzvyAb2IJ,https://www.cheapflights.com/flights-to-hong-k...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.462434,0.46,"137,000,000"
4,flights to hong kong,7,Travelers on United flight to Hong Kong delaye...,"Jan 20, 2019 ... United Airlines flight 179 le...",www.nbcnews.com,https://www.nbcnews.com/storyline/airplane-mod...,2019-02-01 11:26:20.355926+00:00,137000000,NM3461SR2PwJ,https://www.nbcnews.com/.../travelers-united-f...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.462434,0.46,"137,000,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3993,tickets to nice,6,Billetterie Officielle OGC Nice,Filter by type. All; Season tickets; Package; ...,billetterie.ogcnice.com,https://billetterie.ogcnice.com/uk,2019-02-01 11:26:34.741395+00:00,379000000,oOOabhwvUmYJ,https://billetterie.ogcnice.com/uk,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.279275,0.28,"379,000,000"
3994,tickets to nice,7,Cheap flights to Nice from £22 - Book trips to...,The city of Nice is served by the Nice Côte d'...,www.opodo.co.uk,https://www.opodo.co.uk/flights/nice/NCE/,2019-02-01 11:26:34.741395+00:00,379000000,_lZDrsS7w7oJ,https://www.opodo.co.uk/flights/nice/NCE/,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.279275,0.28,"379,000,000"
3995,tickets to nice,8,OGC Nice Tickets | Buy or Sell Tickets for OGC...,OGC Nice tickets now available from £16.64 as ...,www.viagogo.co.uk,https://www.viagogo.co.uk/Sports-Tickets/Footb...,2019-02-01 11:26:34.741395+00:00,379000000,CaSToMNESN4J,https://www.viagogo.co.uk/Sports-Tickets/...1/...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.279275,0.28,"379,000,000"
3996,tickets to nice,9,"5 Cheap Flights to Nice, France (NCE) @ £26 20...",Cheap Flights to Nice: Enter your dates once a...,www.tripadvisor.co.uk,https://www.tripadvisor.co.uk/Flights-g187234-...,2019-02-01 11:26:34.741395+00:00,379000000,1-sONufbuo8J,https://www.tripadvisor.co.uk/Flights-g187234-...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.279275,0.28,"379,000,000"
3997,tickets to nice,10,Flights to Nice (NCE) | KLM Nice tickets from ...,Find the best ticket deals for flights to Nice...,www.klm.com,https://www.klm.com/en-gb/flights-to-nice,2019-02-01 11:26:34.741395+00:00,379000000,Qg3dxkSh2iMJ,https://www.klm.com/en-gb/flights-to-nice,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,uk,0.279275,0.28,"379,000,000"

In [39]:
pd.read_csv("flights_tickets_serp2019-02-01.csv",nrows=45)

,searchTerms,rank,title,snippet,displayLink,link,queryTime,totalResults,cacheId,formattedUrl,...,count,startIndex,inputEncoding,outputEncoding,safe,cx,gl,searchTime,formattedSearchTime,formattedTotalResults
0,flights to hong kong,1,Cheap Flights to Hong Kong (HKG) from $400 - K...,"Find flights to Hong Kong on XiamenAir, Hong K...",www.kayak.com,https://www.kayak.com/flight-routes/United-Sta...,2019-02-01 11:26:20.355926+00:00,137000000,W42baDpas_gJ,https://www.kayak.com/flight-routes/United.../...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.462434,0.46,"137,000,000"
1,flights to hong kong,2,"$500 Flights to Hong Kong, China (HKG) - TripA...",Book Cheap Flights to Hong Kong: Search and co...,www.tripadvisor.com,https://www.tripadvisor.com/Flights-g294217-Ho...,2019-02-01 11:26:20.355926+00:00,137000000,5jsjhmxgxvkJ,https://www.tripadvisor.com/Flights-g294217-Ho...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.462434,0.46,"137,000,000"
2,flights to hong kong,3,Flights to Hong Kong (HKG) | Cathay Pacific,Find & book great deals on Hong Kong (HKG) Fli...,www.cathaypacific.com,https://www.cathaypacific.com/destinations/en_...,2019-02-01 11:26:20.355926+00:00,137000000,UEdjkoYlsQsJ,https://www.cathaypacific.com/destinations/en....,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.462434,0.46,"137,000,000"
3,flights to hong kong,4,Cheap Flights to Hong Kong International from ...,Find cheap flights to Hong Kong International ...,www.skyscanner.com,https://www.skyscanner.com/flights-to/hkg/chea...,2019-02-01 11:26:20.355926+00:00,137000000,EI78TI4Q1qYJ,https://www.skyscanner.com/flights-to/hkg/chea...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.462434,0.46,"137,000,000"
4,flights to hong kong,5,"Cheap Flights to Hong Kong SAR, Asia $165 in 2...",Expedia Add-On Advantage: Book a flight & unlo...,www.expedia.com,https://www.expedia.com/Cheap-Flights-To-Hong-...,2019-02-01 11:26:20.355926+00:00,137000000,iEmRbX0P8CAJ,https://www.expedia.com/Cheap-Flights-To-Hong-...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.462434,0.46,"137,000,000"
5,flights to hong kong,6,Cheap Flights to Hong Kong - Search Deals on A...,Looking for cheap flights to Hong Kong from yo...,www.cheapflights.com,https://www.cheapflights.com/flights-to-hong-k...,2019-02-01 11:26:20.355926+00:00,137000000,INTDzvyAb2IJ,https://www.cheapflights.com/flights-to-hong-k...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.462434,0.46,"137,000,000"
6,flights to hong kong,7,Travelers on United flight to Hong Kong delaye...,"Jan 20, 2019 ... United Airlines flight 179 le...",www.nbcnews.com,https://www.nbcnews.com/storyline/airplane-mod...,2019-02-01 11:26:20.355926+00:00,137000000,NM3461SR2PwJ,https://www.nbcnews.com/.../travelers-united-f...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.462434,0.46,"137,000,000"
7,flights to hong kong,8,"Passenger Arrivals, Flights - Hong Kong Intern...",Real-time information of arrival flights at Ho...,www.hongkongairport.com,https://www.hongkongairport.com/en/flights/arr...,2019-02-01 11:26:20.355926+00:00,137000000,dHRWOA7CXpcJ,https://www.hongkongairport.com/en/flights/arr...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.462434,0.46,"137,000,000"
8,flights to hong kong,9,"Cheap Flights to Hong Kong, Hong Kong (HKG) Fl...",Cheap flights to Hong Kong (HKG) up for grab o...,www.onetravel.com,https://www.onetravel.com/cheap-flights/hong-k...,2019-02-01 11:26:20.355926+00:00,137000000,Ger-cXsOAmYJ,https://www.onetravel.com/...flights/hong-kong...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.462434,0.46,"137,000,000"
9,flights to hong kong,10,$410 + Flights to Hong Kong SAR (HKG) on Orbit...,Flights to Hong Kong SAR (HKG): Search on Orbi...,www.orbitz.com,https://www.orbitz.com/Cheap-Flights-To-Hong-K...,2019-02-01 11:26:20.355926+00:00,137000000,b46GCa9COrMJ,https://www.orbitz.com/Cheap-Flights-To-Hong-K...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.462434,0.46,"137,000,000"
10,flights to bangkok,1,"$438 Flights to Bangkok, Thailand (BKK) - Trip...",Book Cheap Flights to Bangkok: Search and comp...,www.tripadvisor.com,https://www.tripadvisor.com/Flights-g293916-Ba...,2019-02-01 11:26:20.384110+00:00,67700000,FKUIKro9V5EJ,https://www.tripadvisor.com/Flights-g293916-Ba...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.495823,0.50,"67,700,000"
11,flights to bangkok,2,Find Cheap Flights to Bangkok Suvarnabhumi & o...,Suvarnabhumi Airport is connected directly to ...,www.kayak.com,https://www.kayak.com/flight-routes/United-Sta...,2019-02-01 11:26:20.384110+00:00,67700000,je4Wr-SSEKwJ,https://www.kayak.com/flight.../Bangkok-Suvarn...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.495823,0.50,"67,700,000"
12,flights to bangkok,3,"Cheap Flights to Bangkok, Bangkok $398 in 2019...",Expedia Add-On Advantage: Book a flight & unlo...,www.expedia.com,https://www.expedia.com/Cheap-Flights-To-Bangk...,2019-02-01 11:26:20.384110+00:00,67700000,Qj3w00BDzVkJ,https://www.expedia.com/Cheap-Flights-To-Bangk...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.495823,0.50,"67,700,000"
13,flights to bangkok,4,Cheap Flights to Bangkok from $398 - Skyscanner,Cheap Flights to Bangkok. Bangkok is the capit...,www.skyscanner.com,https://www.skyscanner.com/flights-to/bkkt/che...,2019-02-01 11:26:20.384110+00:00,67700000,KB7fF1dbkhIJ,https://www.skyscanner.com/flights.../cheap-fl...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.495823,0.50,"67,700,000"
14,flights to bangkok,5,Cheap Flights To Bangkok Thailand | CheapOair,"Cheap Flights to Bangkok, Thailand (BKK) start...",www.cheapoair.com,https://www.cheapoair.com/flights/cheap-flight...,2019-02-01 11:26:20.384110+00:00,67700000,qAZhkk_2_l4J,https://www.cheapoair.com/flights/cheap-flight...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.495823,0.50,"67,700,000"
15,flights to bangkok,6,$398 + Flights to Bangkok (BKK) on Orbitz.com,Flights to Bangkok (BKK): Search on Orbitz for...,www.orbitz.com,https://www.orbitz.com/Cheap-Flights-To-Bangko...,2019-02-01 11:26:20.384110+00:00,67700000,Dme1ZdxL0UwJ,https://www.orbitz.com/Cheap-Flights-To-Bangko...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.495823,0.50,"67,700,000"
16,flights to bangkok,7,Find Cheap Flights to Bangkok from 380 USD | m...,Looking for flights to Bangkok? Search 1000+ a...,www.momondo.com,https://www.momondo.com/flights/bangkok,2019-02-01 11:26:20.384110+00:00,67700000,bOBqY9hC7FgJ,https://www.momondo.com/flights/bangkok,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.495823,0.50,"67,700,000"
17,flights to bangkok,8,"Cheap Flights to Bangkok, Thailand - Search De...","Looking for cheap flights to Bangkok, Thailand...",www.cheapflights.com,https://www.cheapflights.com/flights-to-bangkok/,2019-02-01 11:26:20.384110+00:00,67700000,g9smzCOORT4J,https://www.cheapflights.com/flights-to-bangkok/,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.495823,0.50,"67,700,000"
18,flights to bangkok,9,"Flights to Bangkok, Thailand : Best Fare Guara...",Visit the beautiful capital of Thailand with D...,www.delta.com,https://www.delta.com/content/www/en_US/travel...,2019-02-01 11:26:20.384110+00:00,67700000,Ve2nyFL7XeYJ,https://www.delta.com/content/www/en_US/.../ba...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.495823,0.50,"67,700,000"
19,flights to bangkok,10,Flights to Bangkok (BKK) | Find and book fligh...,Our guide to the best of Bangkok—where to stay...,www.emirates.com,https://www.emirates.com/us/english/destinatio...,2019-02-01 11:26:20.384110+00:00,67700000,vRTvYP5TgbYJ,https://www.emirates.com/us/english/.../flight...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.495823,0.50,"67,700,000"
20,flights to london,1,Cheap Flights to London (LON) from $256 - KAYAK,"Find flights to London on Finnair, Air Canada,...",www.kayak.com,https://www.kayak.com/flight-routes/United-Sta...,2019-02-01 11:26:20.413480+00:00,354000000,TBPBbAjP93AJ,https://www.kayak.com/flight-routes/United-Sta...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.487089,0.49,"354,000,000"
21,flights to london,2,Cheap Flights to London from £19 in 2019 | Sky...,Find cheap flights to London today. Search for...,www.skyscanner.net,https://www.skyscanner.net/flights-to/lond/che...,2019-02-01 11:26:20.413480+00:00,354000000,vIMA491DMdgJ,https://www.skyscanner.net/flights-to/.../chea...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.487089,0.49,"354,000,000"
22,flights to london,3,"$311 Flights to London, United Kingdom (LON) -...",Book Cheap Flights to London: Search and compa...,www.tripadvisor.com,https://www.tripadvisor.com/Flights-g186338-Lo...,2019-02-01 11:26:20.413480+00:00,354000000,HwvCH3UpM2UJ,https://www.tripadvisor.com/Flights-g186338-Lo...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.487089,0.49,"354,000,000"
23,flights to london,4,Cheap Flights to London from $303 in 2019 | Sk...,Search the cheapest flights to London with top...,www.skyscanner.com,https://www.skyscanner.com/flights-to/lond/che...,2019-02-01 11:26:20.413480+00:00,354000000,AI7SwXp02M4J,https://www.skyscanner.com/flights-to/.../chea...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.487089,0.49,"354,000,000"
24,flights to london,5,"Cheap Flights to London, England (LHR Airport)...",Expedia Add-On Advantage: Book a flight & unlo...,www.expedia.com,https://www.expedia.com/Cheap-Flights-To-Londo...,2019-02-01 11:26:20.413480+00:00,354000000,Ux_3iDA8qkYJ,https://www.expedia.com/Cheap-Flights-To-Londo...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.487089,0.49,"354,000,000"
25,flights to london,6,Cheap flights to London (STN) from €4.99 | Rya...,Looking for great deals on flights to London? ...,www.ryanair.com,https://www.ryanair.com/flights/ie/en/flights-...,2019-02-01 11:26:20.413480+00:00,354000000,NLpG3MyTy1QJ,https://www.ryanair.com/flights/ie/en/flights-...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.487089,0.49,"354,000,000"
26,flights to london,7,Flights to London (LON) $312+ | Direct Flights...,Looking for Cheap Flights to London (LON)? Fin...,www.orbitz.com,https://www.orbitz.com/Cheap-Flights-To-London...,2019-02-01 11:26:20.413480+00:00,354000000,wCYm4qeKVdUJ,https://www.orbitz.com/Cheap-Flights-To-London...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.487089,0.49,"354,000,000"
27,flights to london,8,Cheap Flights to London (LHR) | Icelandair,Icelandair offers cheap flights to London from...,www.icelandair.com,https://www.icelandair.com/flights/london/,2019-02-01 11:26:20.413480+00:00,354000000,6AlB8TvDe3UJ,https://www.icelandair.com/flights/london/,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.487089,0.49,"354,000,000"
28,flights to london,9,"Cheap Flights to London, (LON) Airline Tickets",Cheap Fare on Flights to London (LON) starting...,www.cheapoair.com,https://www.cheapoair.com/flights/cheap-flight...,2019-02-01 11:26:20.413480+00:00,354000000,UFIRJt0bjSkJ,https://www.cheapoair.com/flights/cheap-flight...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.487089,0.49,"354,000,000"
29,flights to london,10,"Flights to London (LHR, LGW, LCY) | Book now w...",Book flights to London with British Airways. O...,www.britishairways.com,https://www.britishairways.com/en-us/destinati...,2019-02-01 11:26:20.413480+00:00,354000000,TBp0lfttJk8J,https://www.britishairways.com/en-us/.../londo...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.487089,0.49,"354,000,000"
30,flights to singapore,1,Cheap Flights to Singapore (SIN) from $394 - K...,"Find flights to Singapore on China Southern, X...",www.kayak.com,https://www.kayak.com/flight-routes/United-Sta...,2019-02-01 11:26:20.448467+00:00,144000000,ioJQt6sNVj4J,https://www.kayak.com/flight-routes/.../Singap...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.398144,0.40,"144,000,000"
31,flights to singapore,2,"Cheap Flights to Singapore, Singapore (SIN Air...",Expedia Add-On Advantage: Book a flight & unlo...,www.expedia.com,https://www.expedia.com/Cheap-Flights-To-Singa...,2019-02-01 11:26:20.448467+00:00,144000000,kU0WJFxkXUkJ,https://www.expedia.com/Cheap-Flights-To-Singa...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.398144,0.40,"144,000,000"
32,flights to singapore,3,"$468 Flights to Singapore, Singapore (SIN) - T...",Cheap Flights to Singapore: Enter your dates o...,www.tripadvisor.com,https://www.tripadvisor.com/Flights-g294265-Si...,2019-02-01 11:26:20.448467+00:00,144000000,RG8GRojZq_QJ,https://www.tripadvisor.com/Flights-g294265-Si...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.398144,0.40,"144,000,000"
33,flights to singapore,4,Singapore Airlines Official Website | Book Int...,Book your flight tickets with Singapore Airlin...,www.singaporeair.com,https://www.singaporeair.com/,2019-02-01 11:26:20.448467+00:00,144000000,NaN,https://www.singaporeair.com/,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.398144,0.40,"144,000,000"
34,flights to singapore,5,Cheap Flights to Singapore Changi from £310 | ...,Flights to Singapore. We compare all major air...,www.skyscanner.net,https://www.skyscanner.net/flights-to/sin/chea...,2019-02-01 11:26:20.448467+00:00,144000000,Uh9Td7kIsuwJ,https://www.skyscanner.net/flights.../cheap-fl...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.398144,0.40,"144,000,000"
35,flights to singapore,6,Flights to Singapore Changi Airport | Skyscann...,Singapore Changi Airport's cluster of gardens ...,www.skyscanner.com.my,https://www.skyscanner.com.my/flights-to/sin/c...,2019-02-01 11:26:20.448467+00:00,144000000,ro0GYcX8PGcJ,https://www.skyscanner.com.my/flights.../cheap...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.398144,0.40,"144,000,000"
36,flights to singapore,7,Cheap Flights to Singapore - Find Airfares to ...,Looking for cheap flights to Singapore? Use We...,www.webjet.com.au,https://www.webjet.com.au/flights/singapore/,2019-02-01 11:26:20.448467+00:00,144000000,vvE1MCeTRzQJ,https://www.webjet.com.au/flights/singapore/,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.398144,0.40,"144,000,000"
37,flights to singapore,8,Cheap Flights to Singapore Changi from $387 in...,Cheap Flight to Singapore People fly in and ou...,www.skyscanner.com,https://www.skyscanner.com/flights-to/sin/chea...,2019-02-01 11:26:20.448467+00:00,144000000,pmlpbdGgLrgJ,https://www.skyscanner.com/flights.../cheap-fl...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.398144,0.40,"144,000,000"
38,flights to singapore,9,Cheap Flights to Singapore - Widest Choice & 2...,"Even if you're just in transit, you're in luck...",www.flightcentre.com.au,https://www.flightcentre.com.au/flights/singapore,2019-02-01 11:26:20.448467+00:00,144000000,wBwKHBlPnZYJ,https://www.flightcentre.com.au/flights/singapore,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.398144,0.40,"144,000,000"
39,flights to singapore,10,Cheap Flights to Singapore (SIN) from £312 - K...,Find flights to Singapore on Shenzhen Airlines...,www.kayak.co.uk,https://www.kayak.co.uk/flight-routes/United-K...,2019-02-01 11:26:20.448467+00:00,144000000,DmLUJgLTzIgJ,https://www.kayak.co.uk/flight-routes/.../Sing...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.398144,0.40,"144,000,000"
40,flights to macau,1,Cheap Flights to Macau (MFM) from $425 - KAYAK,"Find flights to Macau on XiamenAir, China East...",www.kayak.com,https://www.kayak.com/flight-routes/United-Sta...,2019-02-01 11:26:20.478444+00:00,28000000,tcmP5EtIy6wJ,https://www.kayak.com/flight-routes/United-Sta...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.416375,0.42,"28,000,000"
41,flights to macau,2,"Cheap Flights to Macau SAR, Asia $138 in 2019 ...",Expedia Add-On Advantage: Book a flight & unlo...,www.expedia.com,https://www.expedia.com/Cheap-Flights-To-Macau...,2019-02-01 11:26:20.478444+00:00,28000000,1uQDVwfu_-YJ,https://www.expedia.com/Cheap-Flights-To-Macau...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.416375,0.42,"28,000,000"
42,flights to macau,3,"$491 Flights to Macau, China (MFM) - TripAdvisor",Book Cheap Flights to Macau: Search and compar...,www.tripadvisor.com,https://www.tripadvisor.com/Flights-g664891-Ma...,2019-02-01 11:26:20.478444+00:00,28000000,dF0MIH9Buh0J,https://www.tripadvisor.com/Flights-g664891-Ma...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.416375,0.42,"28,000,000"
43,flights to macau,4,Cheap Flights to Macau,"Compare cheap flights to Macau SAR, Asia - Exp...",www.expedia.com.sg,https://www.expedia.com.sg/Cheap-Flights-To-Ma...,2019-02-01 11:26:20.478444+00:00,28000000,1nP4EKX0XRkJ,https://www.expedia.com.sg/Cheap-Flights-To-Ma...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.416375,0.42,"28,000,000"
44,flights to macau,5,Cheap Flights to Macau from £449 | Skyscanner,Flights to Macau. We compare all major airline...,www.skyscanner.net,https://www.skyscanner.net/flights-to/mfm/chea...,2019-02-01 11:26:20.478444+00:00,28000000,XO_2l3-TDdEJ,https://www.skyscanner.net/flights.../cheap-fl...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.416375,0.42,"28,000,000"