In [44]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [45]:
df=pd.read_csv("cars.csv")
df

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [46]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [47]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [48]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

In [49]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [50]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
df.head(3)

    brand  km_driven    fuel         owner  selling_price
0  Maruti     145500  Diesel   First Owner         450000
1   Skoda     120000  Diesel  Second Owner         370000
2   Honda     140000  Petrol   Third Owner         158000

In [51]:
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,:4],df.iloc[:,-1],test_size=0.2,random_state=True)

In [52]:
x_train.shape,y_train.shape

((6502, 4), (6502,))

In [53]:
ohe=OneHotEncoder(drop='first')

In [54]:
x_train_new=ohe.fit_transform(x_train[['fuel','owner']]).toarray()

In [55]:
x_test_new=ohe.fit_transform(x_train[['fuel','owner']]).toarray()

In [56]:
x_train

        brand  km_driven    fuel         owner
1939    Honda     100000  Diesel  Second Owner
5455   Maruti     120000  Diesel  Second Owner
7079  Renault     100000  Diesel  Second Owner
2000    Honda      80000  Petrol  Second Owner
1578    Honda      56494  Petrol   First Owner
...       ...        ...     ...           ...
7935   Maruti     100000  Petrol   Third Owner
5192  Hyundai     152000  Diesel   First Owner
3980  Hyundai      70000  Petrol   First Owner
235    Maruti     110000  Diesel  Second Owner
5157   Maruti      65755  Petrol   First Owner

[6502 rows x 4 columns]

In [57]:
x_train_new.shape

(6502, 7)

In [58]:
x_test

         brand  km_driven    fuel        owner
1392  Mahindra      80000  Diesel  First Owner
7778      Tata      45000  Diesel  First Owner
3727   Hyundai      60000  Diesel  First Owner
6630      Tata      15000  Petrol  First Owner
103     Maruti     100000  Petrol  Third Owner
...        ...        ...     ...          ...
3697    Maruti     120000  Diesel  First Owner
3001   Hyundai     110000  Diesel  Third Owner
94      Maruti      55500  Petrol  First Owner
4535    Maruti      15000  Diesel  First Owner
1610    Maruti      25000  Petrol  First Owner

[1626 rows x 4 columns]

In [59]:
x_test_new.shape

(6502, 7)

In [63]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new))

array([['Honda', 100000, 1.0, ..., 1.0, 0.0, 0.0],
       ['Maruti', 120000, 1.0, ..., 1.0, 0.0, 0.0],
       ['Renault', 100000, 1.0, ..., 1.0, 0.0, 0.0],
       ...,
       ['Hyundai', 70000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 110000, 1.0, ..., 1.0, 0.0, 0.0],
       ['Maruti', 65755, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object)

In [61]:
ohe_df=pd.DataFrame(np.hstack((x_train[['brand','km_driven']].values,x_train_new)))

In [62]:
ohe_df

            0       1    2    3    4    5    6    7    8
0       Honda  100000  1.0  0.0  0.0  0.0  1.0  0.0  0.0
1      Maruti  120000  1.0  0.0  0.0  0.0  1.0  0.0  0.0
2     Renault  100000  1.0  0.0  0.0  0.0  1.0  0.0  0.0
3       Honda   80000  0.0  0.0  1.0  0.0  1.0  0.0  0.0
4       Honda   56494  0.0  0.0  1.0  0.0  0.0  0.0  0.0
...       ...     ...  ...  ...  ...  ...  ...  ...  ...
6497   Maruti  100000  0.0  0.0  1.0  0.0  0.0  0.0  1.0
6498  Hyundai  152000  1.0  0.0  0.0  0.0  0.0  0.0  0.0
6499  Hyundai   70000  0.0  0.0  1.0  0.0  0.0  0.0  0.0
6500   Maruti  110000  1.0  0.0  0.0  0.0  1.0  0.0  0.0
6501   Maruti   65755  0.0  0.0  1.0  0.0  0.0  0.0  0.0

[6502 rows x 9 columns]