# Web Scraping

In [1]:
import pandas as pd

In [40]:
data=pd.read_csv('ambitionbox.csv')
df=pd.DataFrame(data)
data2=pd.read_csv('ambitionbox2.csv')
df2=pd.DataFrame(data2)

In [41]:
df

,Unnamed: 0,CompanyName,Rating,TotalReviews,SalaryOffereByComapany,TotalInterviews,Benefits,PhotosOnSite
0,0,TCS,3.3,1.2L,10.3L,11.4k,11k,93
1,1,Accenture,3.7,74.8k,7.1L,9.5k,6.9k,49
2,2,Wipro,3.6,66.1k,4.9L,6.9k,4.9k,115
3,3,Cognizant,3.7,62.4k,6.1L,6.5k,5.6k,102
4,4,Capgemini,3.6,54.5k,4.9L,5.6k,3.8k,44
...,...,...,...,...,...,...,...,...
3971,3971,Phoenix Contact,4.0,288,1.4k,27,23,1
3972,3972,Ribbon Communication,3.8,288,1.6k,31,34,--
3973,3973,I P Integrated Services,3.8,288,831,13,28,2
3974,3974,Bonn Group,3.9,288,1.1k,16,26,--
3975,3975,360 Degree Cloud Technologies,3.8,288,1.5k,75,10,8

In [42]:
df2

,Unnamed: 0,CompanyName,Rating,TotalReviews,SalaryOffereByComapany,TotalInterviews,Benefits,PhotosOnSite
0,0,Gionee,4.4,288,298,1,55,--
1,1,Jayashree Polymers,3.7,288,1.3k,24,20,1
2,2,Velnik India,3.2,288,1.1k,26,23,1
3,3,Confederation of Indian Industry,3.4,288,1.4k,22,12,--
4,4,Infineon Technologies,3.6,288,2.8k,48,22,6
...,...,...,...,...,...,...,...,...
6010,6010,Applied Solar Technologies India,3.5,112,458,9,6,--
6011,6011,Srei Infrastructure Finance,4.0,112,380,3,9,--
6012,6012,Chanakya IAS Academy,2.6,112,373,3,3,--
6013,6013,Sterling Generators,4.0,112,390,2,12,--
6014,6014,Udaipur Cement Works,3.8,112,495,9,4,--

In [43]:
final_df=pd.concat([df,df2],ignore_index=True)
# final_df = pd.concat([final_df, df], ignore_index=True)

In [44]:
final_df.drop(columns=['Unnamed: 0'],inplace=True)

In [45]:
final_df

,CompanyName,Rating,TotalReviews,SalaryOffereByComapany,TotalInterviews,Benefits,PhotosOnSite
0,TCS,3.3,1.2L,10.3L,11.4k,11k,93
1,Accenture,3.7,74.8k,7.1L,9.5k,6.9k,49
2,Wipro,3.6,66.1k,4.9L,6.9k,4.9k,115
3,Cognizant,3.7,62.4k,6.1L,6.5k,5.6k,102
4,Capgemini,3.6,54.5k,4.9L,5.6k,3.8k,44
...,...,...,...,...,...,...,...
9986,Applied Solar Technologies India,3.5,112,458,9,6,--
9987,Srei Infrastructure Finance,4.0,112,380,3,9,--
9988,Chanakya IAS Academy,2.6,112,373,3,3,--
9989,Sterling Generators,4.0,112,390,2,12,--
9990,Udaipur Cement Works,3.8,112,495,9,4,--

In [46]:
final_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9991 entries, 0 to 9990
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CompanyName             9991 non-null   str
 1   Rating                  9991 non-null   float64
 2   TotalReviews            9991 non-null   object
 3   SalaryOffereByComapany  9991 non-null   str
 4   TotalInterviews         9991 non-null   str
 5   Benefits                9991 non-null   str
 6   PhotosOnSite            9991 non-null   str
dtypes: float64(1), object(1), str(5)
memory usage: 800.5+ KB

In [47]:
print(final_df["TotalReviews"].dtype)

object

In [48]:
def converter(data):
    data=str(data)
    if data=='--':
        return None
    if data.endswith('L'):
        return float(data[:-1])*100000
    elif data.endswith('k'):
        return float(data[:-1])*1000
    else:
        return float(data)*1000
final_df['TotalReviews']=final_df['TotalReviews'].apply(converter)
# final_df['SalaryOffereByComapany']=final_df['SalaryOffereByComapany'].apply(converter)

In [50]:
final_df['SalaryOffereByComapany']=final_df['SalaryOffereByComapany'].apply(converter)

In [52]:
final_df['TotalInterviews']=final_df['TotalInterviews'].apply(converter)

In [54]:
final_df['Benefits']=final_df['Benefits'].apply(converter)

In [55]:
final_df

,CompanyName,Rating,TotalReviews,SalaryOffereByComapany,TotalInterviews,Benefits,PhotosOnSite
0,TCS,3.3,120000.0,1030000.0,11400.0,11000.0,93
1,Accenture,3.7,74800.0,710000.0,9500.0,6900.0,49
2,Wipro,3.6,66100.0,490000.0,6900.0,4900.0,115
3,Cognizant,3.7,62400.0,610000.0,6500.0,5600.0,102
4,Capgemini,3.6,54500.0,490000.0,5600.0,3800.0,44
...,...,...,...,...,...,...,...
9986,Applied Solar Technologies India,3.5,112000.0,458000.0,9000.0,6000.0,--
9987,Srei Infrastructure Finance,4.0,112000.0,380000.0,3000.0,9000.0,--
9988,Chanakya IAS Academy,2.6,112000.0,373000.0,3000.0,3000.0,--
9989,Sterling Generators,4.0,112000.0,390000.0,2000.0,12000.0,--
9990,Udaipur Cement Works,3.8,112000.0,495000.0,9000.0,4000.0,--

In [57]:
final_df.to_csv("completeAmbitionbox.csv")